Refactorings
ErikThorsell/coffee_data_displayer pull request #6
Opened 2021-05-09 21:32 UTC by Jassob

I've played around some with TypeScript and Svelte and this is the result.

It mainly moves stuff around and creates the common Coffee type.

2021-05-10 04:30 UTC, ErikThorsell requested changes
Nicely done :) I have some TS-questions, but functionality wise I think this looks really good.

2021-05-10 04:30 UTC, ErikThorsell commented on src/App.svelte
> +  function filterOn(field: keyof Coffee, value: Coffee[keyof Coffee]) {
Cool, never seen [this](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html) before.

2021-05-10 04:30 UTC, ErikThorsell commented on src/App.svelte
> +    return (c: Coffee) => {
Could you elaborate on this? Not necessarily in the code, but just in a review comment.

I don't quite follow:

1. What `(_: Coffee)` does.
    Is it the same thing as writing `return (value: Coffee)` ?
2. What `=>` after the return statement does.
    I understand some use cases of the fat arrow [link](https://www.typescriptlang.org/docs/handbook/2/functions.html), but I don't find the usage of `=>` in combination with `return` elsewhere.

2021-05-10 04:30 UTC, ErikThorsell commented on src/App.svelte
> +        // countries are lowercased in selection
Is it a bad idea? I was thinking, in the name of uniformity, that it's easier to turn everything to lowercase when it's not being displayed on the webpage.

This being said, I would presume _all_ fields should be handled as on row 27; and row 29 could simply be omitted.

2021-05-10 04:30 UTC, ErikThorsell commented on src/App.svelte
> +  };
_This_ is the kind of `=>` I have seen before.

2021-05-10 04:30 UTC, ErikThorsell commented on src/App.svelte
> +  coffees={$coffees}
What does `$` do here?

2021-05-10 04:32 UTC, ErikThorsell commented
Also, I propose that we merge https://github.com/ErikThorsell/coffee_data_displayer/pull/3 and then redirect this PR to `main`. No need to stay on a branch longer than necessary.

2021-05-10 18:10 UTC, Jassob commented on src/App.svelte
> +  function filterOn(field: keyof Coffee, value: Coffee[keyof Coffee]) {
I've stumbled upon it on one hackathon at work, but never used it myself.

I must admit that I was a bit disappointed that I couldn't express the relation between the type of `field` and the type of `value`, but oh well.

2021-05-10 18:26 UTC, Jassob commented on src/App.svelte
> +        // countries are lowercased in selection
I sort of agree, but since we don't know the uniformity of the data we scrape from the roasters I don't think it is too far fetched to actually process the spelling of the countries to make sure that they all are spelled the same way.

I was actually thinking if we should maybe go one step further and [normalize the unicode representation](https://www.unicode.org/faq/normalization.html) and maybe then even convert it to some ASCII equivalent.
But I think we can wait with that work until we know that we need it :)

2021-05-10 18:30 UTC, Jassob commented on src/App.svelte
> +    return (c: Coffee) => {
> 2. What => after the return statement does.
> I understand some use cases of the fat arrow link, but I don't find the usage of => in combination with return elsewhere.

Just to reiterate on this, the function `filterOn` actually returns a filter function (or predicate), i.e. a function that given a Coffee value returns `true` if the value should be kept and `false` if it should be filtered out.
So the arrow you see here _is_ the same kind of arrow as in the fat arrow functions.

2021-05-10 18:34 UTC, Jassob commented on src/App.svelte
> +  coffees={$coffees}
So I've made use of Svelte's [store API] (basically a way to abstract that data _come from somewhere_), `$coffees` is some magic Svelte syntax that instructs the svelte compiler to generate a subscription to that store and that subscription will be destroyed if the component disappears (for instance if we switch view or whatever). 

It is quite a too-powerful tool for a static list of test coffees, but I thought that we could probably experiment with it and then when we tie it all together we might want to make our DB/whatever we end up using a store as well.

[store api]: https://svelte.dev/tutorial/writable-stores

2021-05-10 18:49 UTC, Jassob commented
> Also, I propose that we merge #3 and then redirect this PR to `main`. No need to stay on a branch longer than necessary.

Sounds good!

2021-05-11 04:03 UTC, ErikThorsell commented on src/App.svelte
> +        // countries are lowercased in selection
Oooh. This is interesting. I'll make an issue out of it.

2021-05-11 04:07 UTC, ErikThorsell approved these changes

2021-05-11 04:21 UTC, Jassob commented
Great job with the CI, it caught I introduced with all my rebasings :star:

2021-05-11 04:26 UTC, merged